variables:
  DOCKER_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
  DIRECTORY: './src/'
include:
  - component: $CI_SERVER_FQDN/websn/ci-templates/dotnet-build@v0.0.15
    inputs:
      stage: build
      docker-image: $DOCKER_IMAGE
      directory: $DIRECTORY
  - component: $CI_SERVER_FQDN/websn/ci-templates/dotnet-test@v0.0.15
    inputs:
      stage: test
      docker-image: $DOCKER_IMAGE
      directory: $DIRECTORY
      dependencies: [ build-job ]
  - component: $CI_SERVER_FQDN/websn/ci-templates/dotnet-deploy@v0.0.15
    inputs:
      stage: deploy
      docker-image: $DOCKER_IMAGE
      directory: $DIRECTORY
      dependencies: [ build-job ]

stages:
- build
- test
- deploy
